snarky_removed_country_comments = {
    "France": [
        "Adieu, France! Who will fill the void of baguettes and diplomacy?",
        "Au revoir, France! The scent of croissants won't be as enticing.",
        "Adieu, France! The Louvre might feel a bit quieter without you.",
        "So long, France! Who'll bring that certain 'je ne sais quoi'?",
        "Goodbye, France! Who'll master the art of surrender in your absence?",
        "À bientôt, France! Who'll sprinkle sophistication in diplomacy?",
        "Tata, France! Who'll take over hosting the chicest soirées?",
        "Adios, France! Without you, will revolutions be less fashionable?",
        "So long, France! Who'll challenge others to duels of wit and wine?",
        "Hasta la vista, France! Will the Eiffel Tower miss your presence?",
    ],
    "Germany": [
        "Auf Wiedersehen, Germany! Prost to missing precision and punctuality.",
        "Tschüss, Germany! Who'll bring that engineering finesse now?",
        "Goodbye, Germany! Who'll lead with such efficient orderliness?",
        "Adieu, Germany! Will the autobahns feel less meticulously planned?",
        "Ciao, Germany! Without you, will sausages lack precision?",
        "Sayonara, Germany! Who'll be as efficient in paperwork now?",
        "Auf Wiedersehen, Germany! Who'll embody the spirit of efficiency?",
        "Adios, Germany! Will punctuality bid us adieu along with you?",
        "Auf Wiedersehen, Germany! Who'll embody precision in strategy?",
        "Hasta luego, Germany! Who'll bring such methodical thought to the table?",
    ],
    "England": [
        "Cheerio, England! Who'll keep the stiff upper lip in place?",
        "Ta-ta, England! Without you, will cricket be as proper?",
        "Fare thee well, England! Who'll keep the monarchy's gossip alive?",
        "Goodbye, England! Will the rain feel a bit lonelier without you?",
        "Cheerio, England! Without you, who'll rule with a cup of tea?",
        "Adieu, England! Who'll carry the torch of British politeness now?",
        "Sayonara, England! Who'll keep the sense of humor so dry?",
        "Cheerio, England! Who'll bring that Oxford charm to negotiations?",
        "So long, England! Who'll captain this ship with such poise?",
        "Tally-ho, England! Who'll bring the royal swagger to the table?",
    ],
    "Russia": [
        "Dosvidanya, Russia! Who'll bear the frosty demeanor now?",
        "Dasvidaniya, Russia! Without you, will the snow feel less inviting?",
        "Farewell, Russia! Who'll master the art of the iron fist in diplomacy?",
        "Goodbye, Russia! Will the bears miss their stern master?",
        "Sayonara, Russia! Who'll bring the vodka-fueled diplomacy?",
        "Dosvidanya, Russia! Without you, will winters be less harsh?",
        "Adieu, Russia! Who'll wield such a cold stare in negotiations?",
        "So long, Russia! Who'll keep the 'mysterious East' allure intact?",
        "Dasvidaniya, Russia! Who'll bring the icy resolve to the table?",
        "Hasta luego, Russia! Who'll match that stoic silence now?",
    ],
    "Italy": [
        "Ciao, Italy! Who'll keep the pasta passion burning?",
        "Addio, Italy! Without you, will the pizzas lack authenticity?",
        "Farewell, Italy! Who'll keep the gelato dreams alive?",
        "Buon viaggio, Italy! Who'll bring the dolce vita charm?",
        "Arrivederci, Italy! Without you, will opera lose its fervor?",
        "Ciao, Italy! Who'll carry the fashion flag with such style?",
        "Addio, Italy! Who'll bring that passionate flair to negotiations?",
        "So long, Italy! Who'll keep the Roman spirit alive and kicking?",
        "Ciao, Italy! Who'll bring the taste of la dolce vita to the table?",
        "Arrivederci, Italy! Who'll add that touch of elegance now?",
    ],
    "Austria": [
        "Auf Wiedersehen, Austria! Who'll waltz through diplomacy now?",
        "Tschüss, Austria! Without you, will the Viennese charm fade?",
        "Farewell, Austria! Who'll keep diplomacy as melodious?",
        "Adieu, Austria! Who'll bring the Habsburg elegance to negotiations?",
        "Auf Wiedersehen, Austria! Without you, will the Alps feel silent?",
        "Sayonara, Austria! Who'll conduct the symphony of politics?",
        "Tata, Austria! Who'll bring that imperial allure to the table?",
        "Adios, Austria! Who'll carry the legacy of musical diplomacy?",
        "Auf Wiedersehen, Austria! Who'll lead with such aristocratic grace?",
        "Hasta la vista, Austria! Who'll keep the alpine finesse alive?",
    ],
    "Turkey": [
        "Hoşça kal, Turkey! Who'll spice up diplomacy now?",
        "Güle güle, Turkey! Without you, will kebabs lose their flavor?",
        "Farewell, Turkey! Who'll bring the Ottoman grandeur to negotiations?",
        "Güle güle, Turkey! Who'll brew the coffee of diplomacy?",
        "Hoşça kal, Turkey! Without you, will the Bosphorus feel quieter?",
        "Adieu, Turkey! Who'll bring that Middle Eastern intrigue?",
        "Sayonara, Turkey! Who'll carry the crescent moon in negotiations?",
        "Güle güle, Turkey! Who'll add that touch of spice to the table?",
        "Hoşça kal, Turkey! Who'll blend the East and West so seamlessly?",
        "Güle güle, Turkey! Who'll bring that Anatolian mystique now?",
    ],
    "Other": [
        "Another one bites the dust! The game marches on amidst departures.",
        "A nation's departure changes the course of history.",
        "Goodbye, another nation! Who'll step into the void left behind?",
        "So long, departing nation! Who'll rewrite the pages of diplomacy?",
        "Adieu, departed nation! The game of power continues its ruthless march.",
        "Farewell, vanishing nation! Who'll seize the opportunities born of absence?",
        "Departure echoes through the halls of diplomacy, leaving uncertainty in its wake.",
        "Another departure reshapes the political landscape. Who'll exploit the vacuum?",
        "The departure of a nation alters the symphony of alliances and betrayals.",
        "A seat at the table empty. Who'll vie for the power it once held?",
    ],
}


diplomacy_loading_messages = [
    "Negotiations ongoing... Establishing alliances and plotting strategies.",
    "Diplomatic envoys dispatched... Patience is key in the art of negotiation.",
    "Preparing diplomatic maneuvers... Trust and deceit dance in the realm of diplomacy.",
    "Scheming in progress... Power dynamics shift with every whispered promise.",
    "Conversations in motion... The game of diplomacy thrives on shrewdness.",
    "Alliances being forged... The battlefield of politics is ever dynamic.",
    "Delicate negotiations underway... Words hold the power to shape destinies.",
    "Strategic discussions intensify... Trust is a luxury in the game of diplomacy.",
    "Diplomatic overtures in play... Will you forge bonds or manipulate destinies?",
    "Machiavellian schemes unravel... Each move a step closer to domination.",
    "Intrigue echoes in corridors... Choose your allies wisely.",
    "Secrets exchanged in whispers... Influence wields the sharpest blade.",
    "Trust, the currency of diplomacy... Spend it wisely, if at all.",
    "Chaos underlies diplomacy... Seek opportunity amidst the upheaval.",
    "Strategy born in negotiation... Every word shapes the game's landscape.",
    "The art of persuasion underway... Deception and honesty vie for supremacy.",
    "Shadows cast by clandestine deals... Who can be trusted in this dance?",
    "Diplomatic ballet in motion... Balance and finesse define success.",
    "Political chessboard set... Pawns maneuver in pursuit of power.",
    "Echoes of diplomacy resound... Calculated moves shape the future.",
    "Silent alliances form... Loyalty and betrayal walk hand in hand.",
    "Tides of influence ebb and flow... Who will navigate this sea of power?",
    "Conspiracies weave their web... Each thread a potential advantage.",
    "Diplomatic theater in progress... Masks hide intentions beneath smiles.",
    "Words wield power... But actions determine fates.",
    "Artful negotiation at its peak... Silence often speaks louder.",
    "Theater of diplomacy opens... Spectators unaware of the backstage drama.",
    "Echoes of ambition reverberate... Will trust or treachery reign supreme?",
    "Lies dressed as truth... Trust your instincts amidst deceit.",
    "Strategic gambits underway... Risk and reward dance in the political arena.",
    "Whispers of allegiance heard... But can they weather the storm of conflict?",
    "Silhouettes in negotiation... Shadows hide intentions in this delicate dance.",
    "Strategy and guile interweave... Who will emerge victorious?",
    "Diplomatic ballet in progress... Graceful movements hide calculated steps.",
    "In the arena of politics... One must be both lion and fox.",
    "Diplomatic chess pieces move... Each maneuver alters the landscape.",
    "Subtle alliances take shape... Tread carefully, for trust is scarce.",
    "Intrigue at every turn... Each move a step closer to triumph.",
    "Trust, the ultimate currency... Spend it wisely or watch it crumble.",
    "The heartbeat of diplomacy... Every decision echoes through time.",
    "Whispers of intrigue swirl... The game of power is ever enticing.",
    "Masks of diplomacy worn... True intentions veiled behind smiles.",
    "Treachery lurks in shadows... Be vigilant amidst the intrigue.",
    "In the realm of politics... Allies today might be foes tomorrow.",
    "The dance of diplomacy begins... Every step a calculated move.",
    "Whispers carry weight... Choose your words with care.",
    "Diplomatic maneuvers executed... The stage set for grand performances.",
    "Eyes watch, ears listen... For in silence lies opportunity.",
    "Ambition fuels negotiations... But trust solidifies alliances.",
    "The game of diplomacy unfolds... Each turn a new chapter in history.",
]
